FROM openjdk:17
COPY /target/block16-01-spring-app-viaje-cliente-0.0.1-SNAPSHOT.jar block16-01-spring-app-viaje-cliente-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "block16-01-spring-app-viaje-cliente-0.0.1-SNAPSHOT.jar"]