version: "3.2"

services:
  block16-01-spring-app-viaje-cliente:
    image: block16-01-spring-app-viaje-cliente-image
    build: ./block16-01-spring-app-viaje-cliente
    container_name: block16-01-spring-app-viaje-cliente-contenedor
    ports: 
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://block16-03-eureka-naming-server-contenedor:8761/eureka/
    networks:
      - red-cloud


  block16-02-spring-app-ticket:
    image: block16-02-spring-app-ticket-image
    build: ./block16-02-spring-app-ticket
    container_name: block16-02-spring-app-ticket-contenedor
    ports: 
     - "8082:8082"
    environment:
      - restTemplate.url=http://block16-01-spring-app-viaje-cliente-contenedor:8081/cliente/
      - feignViaje.url=http://block16-01-spring-app-viaje-cliente-contenedor:8081
      - eureka.client.serviceUrl.defaultZone=http://block16-03-eureka-naming-server-contenedor:8761/eureka/
    networks:
      - red-cloud



  block16-03-eureka-naming-server:
    image: block16-03-eureka-naming-server-image
    build: ./block16-03-eureka-naming-server
    container_name: block16-03-eureka-naming-server-contenedor
    ports: 
      - "8761:8761"
    networks:
      - red-cloud



  block16-04-api-gateway:
    image: block16-04-api-gateway-image
    build: ./block16-04-api-gateway
    container_name: block16-04-api-gateway-contenedor
    ports: 
      - "8080:8080"
    environment:
      - spring.cloud.gateway.routes[0].id=cliente
      - spring.cloud.gateway.routes[0].uri=http://block16-01-spring-app-viaje-cliente-contenedor:8081/
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/cliente/**
      - spring.cloud.gateway.routes[1].id=trip
      - spring.cloud.gateway.routes[1].uri=http://block16-01-spring-app-viaje-cliente-contenedor:8081/
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/trip/**
      - spring.cloud.gateway.routes[2].id=ticket
      - spring.cloud.gateway.routes[2].uri=http://block16-02-spring-app-ticket-contenedor:8082/
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/ticket/**
      - eureka.client.serviceUrl.defaultZone= http://block16-03-eureka-naming-server-contenedor:8761/eureka
    networks:
      - red-cloud
    
networks:
  red-cloud:
    driver: bridge