FROM openjdk:17
COPY /target/block16-03-eureka-naming-server-0.0.1-SNAPSHOT.jar block16-03-eureka-naming-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "block16-03-eureka-naming-server-0.0.1-SNAPSHOT.jar"]