FROM openjdk:17
COPY /target/block16-02-spring-app-ticket-0.0.1-SNAPSHOT.jar block16-02-spring-app-ticket-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "block16-02-spring-app-ticket-0.0.1-SNAPSHOT.jar"]